language: objective-c
osx_image: xcode11.0
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator13.0
script:
  - xcodebuild -showsdks
  - xcodebuild -workspace NextLevelSessionExporter.xcworkspace -scheme 'Debug' -sdk $IOS_SDK build analyze
